/**Generated by running: java org.unavco.projects.gsac.repository.UnavcoGsacDatabaseManager**/

package org.ring.gsac.database;

import ucar.unidata.sql.SqlUtil;

//J-
public abstract class Tables {
    public abstract String getName();
    public abstract String getColumns();


    public static class AGENCY extends Tables {
        public static final String NAME = "Agency";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_AGENCYID =  NAME + ".AgencyID";
        public static final String COL_AGENCYNAME =  NAME + ".AgencyName";

        public static final String[] ARRAY = new String[] {
            COL_AGENCYID,COL_AGENCYNAME
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final AGENCY table  = new  AGENCY();
    }



    public static class AGENCYUSER extends Tables {
        public static final String NAME = "AgencyUser";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_AGENCYUSERID =  NAME + ".AgencyUserID";
        public static final String COL_AGENCYID =  NAME + ".AgencyID";
        public static final String COL_LOGINID =  NAME + ".LoginID";
        public static final String COL_PASSWORD =  NAME + ".Password";
        public static final String COL_EMAIL =  NAME + ".Email";
        public static final String COL_FIRSTNAME =  NAME + ".FirstName";
        public static final String COL_LASTNAME =  NAME + ".LastName";
        public static final String COL_SYSADMIN =  NAME + ".Sysadmin";
        public static final String COL_ACTIVE =  NAME + ".Active";

        public static final String[] ARRAY = new String[] {
            COL_AGENCYUSERID,COL_AGENCYID,COL_LOGINID,COL_PASSWORD,COL_EMAIL,COL_FIRSTNAME,COL_LASTNAME,COL_SYSADMIN,COL_ACTIVE
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final AGENCYUSER table  = new  AGENCYUSER();
    }



    public static class AGENCYUSER_TO_SITELOG_MASTER extends Tables {
        public static final String NAME = "AgencyUser_to_SiteLog_Master";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_AGENCYUSERID =  NAME + ".AgencyUserID";
        public static final String COL_FOURID =  NAME + ".FourID";

        public static final String[] ARRAY = new String[] {
            COL_AGENCYUSERID,COL_FOURID
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final AGENCYUSER_TO_SITELOG_MASTER table  = new  AGENCYUSER_TO_SITELOG_MASTER();
    }



    public static class CENTRE_DATA extends Tables {
        public static final String NAME = "Centre_Data";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_INSTITUTION_NAME =  NAME + ".institution_name";
        public static final String COL_ACRONYM =  NAME + ".acronym";
        public static final String COL_INTERNAL_ABBREVATION =  NAME + ".internal_abbrevation";
        public static final String COL_NETWORK =  NAME + ".network";
        public static final String COL_AREA =  NAME + ".area";
        public static final String COL_DAILY_DATA =  NAME + ".daily_data";
        public static final String COL_HOURLY_DATA =  NAME + ".hourly_data";
        public static final String COL_COUNTRY =  NAME + ".country";
        public static final String COL_FTP_ADDRESS =  NAME + ".ftp_address";
        public static final String COL_FTP_USERID =  NAME + ".ftp_userid";
        public static final String COL_FTP_PASSWORD =  NAME + ".ftp_password";
        public static final String COL_DAILY_DATA_HOLDING_FILENAME_AT_DC =  NAME + ".daily_data_holding_filename_at_dc";
        public static final String COL_DAILY_DATA_HOLDING_FILENAME_AT_EPNCB =  NAME + ".daily_data_holding_filename_at_epncb";
        public static final String COL_DAILY_DATA_HOLDING_PATH_AT_DC =  NAME + ".daily_data_holding_path_at_dc";
        public static final String COL_HOURLY_DATA_HOLDING_FILENAME_AT_DC =  NAME + ".hourly_data_holding_filename_at_dc";
        public static final String COL_HOURLY_DATA_HOLDING_FILENAME_AT_EPNCB =  NAME + ".hourly_data_holding_filename_at_epncb";
        public static final String COL_HOURLY_DATA_HOLDING_PATH_AT_DC =  NAME + ".hourly_data_holding_path_at_dc";
        public static final String COL_DAILY_DATA_MAIN_DIRECTORY =  NAME + ".daily_data_main_directory";
        public static final String COL_DAILY_DATA_SUB_DIRECTORY =  NAME + ".daily_data_sub_directory";
        public static final String COL_HOURLY_DATA_ROOT_DIRECTORY =  NAME + ".hourly_data_root_directory";
        public static final String COL_HOURLY_DATA_SUB_DIRECTORY =  NAME + ".hourly_data_sub_directory";
        public static final String COL_DAILY_DATA_ROOT_DIRECTORY =  NAME + ".daily_data_root_directory";
        public static final String COL_DAILY_DATA_PATH_DIRECTORY =  NAME + ".daily_data_path_directory";
        public static final String COL_DAILY_DATA_FILENAME_CASE =  NAME + ".daily_data_filename_case";
        public static final String COL_PLACEOFCOLUMNSIZE_4_LS_ON_FTP =  NAME + ".placeofcolumnsize_4_ls_on_ftp";
        public static final String COL_PLACEOFCOLUMNFILENAME_4_LS_ON_FTP =  NAME + ".placeofcolumnfilename_4_ls_on_ftp";
        public static final String COL_HOURLY_DATA_SESSION_CASE =  NAME + ".hourly_data_session_case";
        public static final String COL_DESCRIPTION =  NAME + ".Description";
        public static final String COL_STATUS =  NAME + ".status";

        public static final String[] ARRAY = new String[] {
            COL_INSTITUTION_NAME,COL_ACRONYM,COL_INTERNAL_ABBREVATION,COL_NETWORK,COL_AREA,COL_DAILY_DATA,COL_HOURLY_DATA,COL_COUNTRY,COL_FTP_ADDRESS,COL_FTP_USERID,COL_FTP_PASSWORD,COL_DAILY_DATA_HOLDING_FILENAME_AT_DC,COL_DAILY_DATA_HOLDING_FILENAME_AT_EPNCB,COL_DAILY_DATA_HOLDING_PATH_AT_DC,COL_HOURLY_DATA_HOLDING_FILENAME_AT_DC,COL_HOURLY_DATA_HOLDING_FILENAME_AT_EPNCB,COL_HOURLY_DATA_HOLDING_PATH_AT_DC,COL_DAILY_DATA_MAIN_DIRECTORY,COL_DAILY_DATA_SUB_DIRECTORY,COL_HOURLY_DATA_ROOT_DIRECTORY,COL_HOURLY_DATA_SUB_DIRECTORY,COL_DAILY_DATA_ROOT_DIRECTORY,COL_DAILY_DATA_PATH_DIRECTORY,COL_DAILY_DATA_FILENAME_CASE,COL_PLACEOFCOLUMNSIZE_4_LS_ON_FTP,COL_PLACEOFCOLUMNFILENAME_4_LS_ON_FTP,COL_HOURLY_DATA_SESSION_CASE,COL_DESCRIPTION,COL_STATUS
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final CENTRE_DATA table  = new  CENTRE_DATA();
    }



    public static class CENTRE_OPERATIONAL extends Tables {
        public static final String NAME = "Centre_Operational";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_NUMBER =  NAME + ".number";
        public static final String COL_ACRONYM =  NAME + ".acronym";
        public static final String COL_PASSWORD =  NAME + ".password";

        public static final String[] ARRAY = new String[] {
            COL_NUMBER,COL_ACRONYM,COL_PASSWORD
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final CENTRE_OPERATIONAL table  = new  CENTRE_OPERATIONAL();
    }



    public static class COUNTRIES extends Tables {
        public static final String NAME = "Countries";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_NAME =  NAME + ".Name";
        public static final String COL_ACRONYM =  NAME + ".Acronym";
        public static final String COL_NETWORK =  NAME + ".Network";

        public static final String[] ARRAY = new String[] {
            COL_NAME,COL_ACRONYM,COL_NETWORK
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final COUNTRIES table  = new  COUNTRIES();
    }



    public static class DEFAULTVALUES extends Tables {
        public static final String NAME = "DefaultValues";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_DEFAULTVALUE =  NAME + ".DefaultValue";

        public static final String[] ARRAY = new String[] {
            COL_DEFAULTVALUE
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final DEFAULTVALUES table  = new  DEFAULTVALUES();
    }



    public static class EQUIPMENT extends Tables {
        public static final String NAME = "Equipment";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_EQUIPMENTID =  NAME + ".EquipmentID";
        public static final String COL_EQUIPMENTTYPEID =  NAME + ".EquipmentTypeID";
        public static final String COL_MODEL =  NAME + ".Model";
        public static final String COL_DESCRIPTION =  NAME + ".Description";
        public static final String COL_EQUIPMENTSTATEID =  NAME + ".EquipmentStateID";
        public static final String COL_EQUIPMANID =  NAME + ".EquipManID";

        public static final String[] ARRAY = new String[] {
            COL_EQUIPMENTID,COL_EQUIPMENTTYPEID,COL_MODEL,COL_DESCRIPTION,COL_EQUIPMENTSTATEID,COL_EQUIPMANID
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final EQUIPMENT table  = new  EQUIPMENT();
    }



    public static class EQUIPMENTMANUFACTURER extends Tables {
        public static final String NAME = "EquipmentManufacturer";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_EQUIPMANID =  NAME + ".EquipManID";
        public static final String COL_EQUIPMANNAME =  NAME + ".EquipManName";

        public static final String[] ARRAY = new String[] {
            COL_EQUIPMANID,COL_EQUIPMANNAME
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final EQUIPMENTMANUFACTURER table  = new  EQUIPMENTMANUFACTURER();
    }



    public static class EQUIPMENTSTATE extends Tables {
        public static final String NAME = "EquipmentState";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_EQUIPMENTSTATEID =  NAME + ".EquipmentStateID";
        public static final String COL_EQUIPMENTSTATE =  NAME + ".EquipmentState";

        public static final String[] ARRAY = new String[] {
            COL_EQUIPMENTSTATEID,COL_EQUIPMENTSTATE
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final EQUIPMENTSTATE table  = new  EQUIPMENTSTATE();
    }



    public static class EQUIPMENTTYPE extends Tables {
        public static final String NAME = "EquipmentType";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_EQUIPMENTTYPEID =  NAME + ".EquipmentTypeID";
        public static final String COL_EQUIPMENTTYPE =  NAME + ".EquipmentType";

        public static final String[] ARRAY = new String[] {
            COL_EQUIPMENTTYPEID,COL_EQUIPMENTTYPE
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final EQUIPMENTTYPE table  = new  EQUIPMENTTYPE();
    }



    public static class FORMCONFIGURATION extends Tables {
        public static final String NAME = "FormConfiguration";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_TABLENAME =  NAME + ".TableName";
        public static final String COL_NEWFORMHEADER =  NAME + ".NewFormHeader";
        public static final String COL_NEWFORMFOOTER =  NAME + ".NewFormFooter";
        public static final String COL_EDITFORMHEADER =  NAME + ".EditFormHeader";
        public static final String COL_EDITFORMFOOTER =  NAME + ".EditFormFooter";
        public static final String COL_AUDITLOGLISTHEADER =  NAME + ".AuditLogListHeader";
        public static final String COL_HISTORYLISTHEADER =  NAME + ".HistoryListHeader";

        public static final String[] ARRAY = new String[] {
            COL_TABLENAME,COL_NEWFORMHEADER,COL_NEWFORMFOOTER,COL_EDITFORMHEADER,COL_EDITFORMFOOTER,COL_AUDITLOGLISTHEADER,COL_HISTORYLISTHEADER
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final FORMCONFIGURATION table  = new  FORMCONFIGURATION();
    }



    public static class FORMFIELDCONFIGURATION extends Tables {
        public static final String NAME = "FormFieldConfiguration";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_TABLENAME =  NAME + ".TableName";
        public static final String COL_FORMFIELDLABEL =  NAME + ".FormFieldLabel";
        public static final String COL_FORMFIELDATTRIBUTES =  NAME + ".FormFieldAttributes";
        public static final String COL_DBFIELDNAME =  NAME + ".DBFieldName";
        public static final String COL_FORMFIELDDEFAULTVALUE =  NAME + ".FormFieldDefaultValue";
        public static final String COL_FORMPOSITIONORDER =  NAME + ".FormPositionOrder";
        public static final String COL_FORMFIELDTYPE =  NAME + ".FormFieldType";
        public static final String COL_FORMLOOKUPSQL =  NAME + ".FormLookupSQL";
        public static final String COL_FORMFIELDTOOLTIP =  NAME + ".FormFieldToolTip";
        public static final String COL_FORMFIELDATTRIBUTES_SAVE =  NAME + ".FormFieldAttributes_save";

        public static final String[] ARRAY = new String[] {
            COL_TABLENAME,COL_FORMFIELDLABEL,COL_FORMFIELDATTRIBUTES,COL_DBFIELDNAME,COL_FORMFIELDDEFAULTVALUE,COL_FORMPOSITIONORDER,COL_FORMFIELDTYPE,COL_FORMLOOKUPSQL,COL_FORMFIELDTOOLTIP,COL_FORMFIELDATTRIBUTES_SAVE
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final FORMFIELDCONFIGURATION table  = new  FORMFIELDCONFIGURATION();
    }



    public static class INSTRUMENTATION extends Tables {
        public static final String NAME = "Instrumentation";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_INSTRUTYPE =  NAME + ".InstruType";

        public static final String[] ARRAY = new String[] {
            COL_INSTRUTYPE
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final INSTRUMENTATION table  = new  INSTRUMENTATION();
    }



    public static class RECEIVER extends Tables {
        public static final String NAME = "Receiver";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_TYPE =  NAME + ".Type";
        public static final String COL_SATELLITESYSTEM =  NAME + ".SatelliteSystem";

        public static final String[] ARRAY = new String[] {
            COL_TYPE,COL_SATELLITESYSTEM
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final RECEIVER table  = new  RECEIVER();
    }



    public static class SITELOG_ANTENNA extends Tables {
        public static final String NAME = "SiteLog_Antenna";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_ID =  NAME + ".ID";
        public static final String COL_ANTENNATYPE =  NAME + ".AntennaType";
        public static final String COL_SERIALNUMBERANTENNA =  NAME + ".SerialNumberAntenna";
        public static final String COL_ANTENNAREFPOINT =  NAME + ".AntennaRefPoint";
        public static final String COL_MARKERUP =  NAME + ".MarkerUp";
        public static final String COL_MARKERNORTH =  NAME + ".MarkerNorth";
        public static final String COL_MARKEREST =  NAME + ".MarkerEst";
        public static final String COL_ALIGNEMENT =  NAME + ".Alignement";
        public static final String COL_ANTENNARADOMETYPE =  NAME + ".AntennaRadomeType";
        public static final String COL_RADOMESERIALNUMBER =  NAME + ".RadomeSerialNumber";
        public static final String COL_ANTENNACABLETYPE =  NAME + ".AntennaCableType";
        public static final String COL_ANTENNACABLELENGTH =  NAME + ".AntennaCableLength";
        public static final String COL_DATEINSTALLEDANTENNA =  NAME + ".DateInstalledAntenna";
        public static final String COL_DATEREMOVEDANTENNA =  NAME + ".DateRemovedAntenna";
        public static final String COL_ADDINFOANTENNA =  NAME + ".AddInfoAntenna";
        public static final String COL_FOURID =  NAME + ".FourID";

        public static final String[] ARRAY = new String[] {
            COL_ID,COL_ANTENNATYPE,COL_SERIALNUMBERANTENNA,COL_ANTENNAREFPOINT,COL_MARKERUP,COL_MARKERNORTH,COL_MARKEREST,COL_ALIGNEMENT,COL_ANTENNARADOMETYPE,COL_RADOMESERIALNUMBER,COL_ANTENNACABLETYPE,COL_ANTENNACABLELENGTH,COL_DATEINSTALLEDANTENNA,COL_DATEREMOVEDANTENNA,COL_ADDINFOANTENNA,COL_FOURID
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final SITELOG_ANTENNA table  = new  SITELOG_ANTENNA();
    }



    public static class SITELOG_ANTENNAGRAPHICS extends Tables {
        public static final String NAME = "SiteLog_AntennaGraphics";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_FOURID =  NAME + ".FourID";
        public static final String COL_ANTENNAGRAPH =  NAME + ".AntennaGraph";

        public static final String[] ARRAY = new String[] {
            COL_FOURID,COL_ANTENNAGRAPH
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final SITELOG_ANTENNAGRAPHICS table  = new  SITELOG_ANTENNAGRAPHICS();
    }



    public static class SITELOG_AUTHOR extends Tables {
        public static final String NAME = "SiteLog_Author";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_FOURID =  NAME + ".FourID";
        public static final String COL_PREPAREDBY =  NAME + ".PreparedBy";
        public static final String COL_DATEPREPARED =  NAME + ".DatePrepared";
        public static final String COL_REPORTTYPE =  NAME + ".ReportType";
        public static final String COL_CURRENTLOGFILENAME =  NAME + ".CurrentLogFileName";
        public static final String COL_PREVIOUSLOG =  NAME + ".PreviousLog";
        public static final String COL_MODIFIEDSECTION =  NAME + ".ModifiedSection";

        public static final String[] ARRAY = new String[] {
            COL_FOURID,COL_PREPAREDBY,COL_DATEPREPARED,COL_REPORTTYPE,COL_CURRENTLOGFILENAME,COL_PREVIOUSLOG,COL_MODIFIEDSECTION
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final SITELOG_AUTHOR table  = new  SITELOG_AUTHOR();
    }



    public static class SITELOG_CALIBRATIONEXCEPTIONS extends Tables {
        public static final String NAME = "SiteLog_CalibrationExceptions";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_STATIONMARKERNAME =  NAME + ".stationmarkername";
        public static final String COL_ANTENNATYPE =  NAME + ".antennatype";
        public static final String COL_SN =  NAME + ".SN";
        public static final String COL_SUBSECTION =  NAME + ".subsection";
        public static final String COL_COMMENT =  NAME + ".comment";

        public static final String[] ARRAY = new String[] {
            COL_STATIONMARKERNAME,COL_ANTENNATYPE,COL_SN,COL_SUBSECTION,COL_COMMENT
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final SITELOG_CALIBRATIONEXCEPTIONS table  = new  SITELOG_CALIBRATIONEXCEPTIONS();
    }



    public static class SITELOG_COLLOCATION extends Tables {
        public static final String NAME = "SiteLog_Collocation";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_ID =  NAME + ".ID";
        public static final String COL_INSTRUTYPE =  NAME + ".InstruType";
        public static final String COL_STATUS =  NAME + ".Status";
        public static final String COL_EFFDATECOLLOCATION =  NAME + ".EffDateCollocation";
        public static final String COL_ADDINFOCOLLOCATION =  NAME + ".AddInfoCollocation";
        public static final String COL_FOURID =  NAME + ".FourID";
        public static final String COL_EFFSTARTDATECOLLOCATION =  NAME + ".EffStartDateCollocation";
        public static final String COL_EFFENDDATECOLLOCATION =  NAME + ".EffEndDateCollocation";
        public static final String COL_EFFTEMPDATECOLLOCATION =  NAME + ".EffTempDateCollocation";

        public static final String[] ARRAY = new String[] {
            COL_ID,COL_INSTRUTYPE,COL_STATUS,COL_EFFDATECOLLOCATION,COL_ADDINFOCOLLOCATION,COL_FOURID,COL_EFFSTARTDATECOLLOCATION,COL_EFFENDDATECOLLOCATION,COL_EFFTEMPDATECOLLOCATION
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final SITELOG_COLLOCATION table  = new  SITELOG_COLLOCATION();
    }



    public static class SITELOG_DATACENTER extends Tables {
        public static final String NAME = "SiteLog_DataCenter";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_FOURID =  NAME + ".FourID";
        public static final String COL_PRIMARYDATACENTER =  NAME + ".PrimaryDataCenter";
        public static final String COL_SECONDARYDATACENTER =  NAME + ".SecondaryDataCenter";
        public static final String COL_URLMOREINFO =  NAME + ".URLMoreInfo";
        public static final String COL_SITEMAP =  NAME + ".SiteMap";
        public static final String COL_SITEDIAGRAM =  NAME + ".SiteDiagram";
        public static final String COL_HORIZONMASK =  NAME + ".horizonMask";
        public static final String COL_MONUMENTDESCRIPTION =  NAME + ".MonumentDescription";
        public static final String COL_SITEPICTURE =  NAME + ".SitePicture";
        public static final String COL_ADDINFO13 =  NAME + ".AddInfo13";

        public static final String[] ARRAY = new String[] {
            COL_FOURID,COL_PRIMARYDATACENTER,COL_SECONDARYDATACENTER,COL_URLMOREINFO,COL_SITEMAP,COL_SITEDIAGRAM,COL_HORIZONMASK,COL_MONUMENTDESCRIPTION,COL_SITEPICTURE,COL_ADDINFO13
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final SITELOG_DATACENTER table  = new  SITELOG_DATACENTER();
    }



    public static class SITELOG_FORMEVENTS extends Tables {
        public static final String NAME = "SiteLog_FormEvents";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_ID =  NAME + ".Id";
        public static final String COL_DATE =  NAME + ".Date";
        public static final String COL_BUTTON =  NAME + ".Button";
        public static final String COL_OC =  NAME + ".OC";
        public static final String COL_STATION =  NAME + ".Station";
        public static final String COL_COMMENT =  NAME + ".Comment";

        public static final String[] ARRAY = new String[] {
            COL_ID,COL_DATE,COL_BUTTON,COL_OC,COL_STATION,COL_COMMENT
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final SITELOG_FORMEVENTS table  = new  SITELOG_FORMEVENTS();
    }



    public static class SITELOG_FREQUENCYSTANDARD extends Tables {
        public static final String NAME = "SiteLog_FrequencyStandard";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_ID =  NAME + ".ID";
        public static final String COL_STANDARDTYPE =  NAME + ".StandardType";
        public static final String COL_INPUTFREQUENCY =  NAME + ".InputFrequency";
        public static final String COL_EFFDATEFREQUENCY =  NAME + ".EffdateFrequency";
        public static final String COL_ADDINFOFREQUENCY =  NAME + ".AddInfoFrequency";
        public static final String COL_FOURID =  NAME + ".FourID";
        public static final String COL_EFFSTARTDATEFREQUENCY =  NAME + ".EffStartDateFrequency";
        public static final String COL_EFFENDDATEFREQUENCY =  NAME + ".EffEndDateFrequency";
        public static final String COL_EFFTEMPDATEFREQUENCY =  NAME + ".EffTempDateFrequency";

        public static final String[] ARRAY = new String[] {
            COL_ID,COL_STANDARDTYPE,COL_INPUTFREQUENCY,COL_EFFDATEFREQUENCY,COL_ADDINFOFREQUENCY,COL_FOURID,COL_EFFSTARTDATEFREQUENCY,COL_EFFENDDATEFREQUENCY,COL_EFFTEMPDATEFREQUENCY
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final SITELOG_FREQUENCYSTANDARD table  = new  SITELOG_FREQUENCYSTANDARD();
    }



    public static class SITELOG_HUMIDITYSENSOR extends Tables {
        public static final String NAME = "SiteLog_HumiditySensor";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_ID =  NAME + ".ID";
        public static final String COL_HUMIDITYSENSOR =  NAME + ".HumiditySensor";
        public static final String COL_MANUFACTURER =  NAME + ".Manufacturer";
        public static final String COL_SERIALNUMBERSENSOR =  NAME + ".SerialNumberSensor";
        public static final String COL_DATASAMPLINGSENSOR =  NAME + ".DataSamplingSensor";
        public static final String COL_ACCURACY =  NAME + ".Accuracy";
        public static final String COL_ASPIRATION =  NAME + ".Aspiration";
        public static final String COL_HEIGHTDIFFSENSOR =  NAME + ".HeightDiffSensor";
        public static final String COL_CALIDATE =  NAME + ".Calidate";
        public static final String COL_EFFDATEHUM =  NAME + ".EffDateHum";
        public static final String COL_ADDINFOHUMIDITY =  NAME + ".AddInfoHumidity";
        public static final String COL_FOURID =  NAME + ".FourID";
        public static final String COL_EFFSTARTDATEHUM =  NAME + ".EffStartDateHum";
        public static final String COL_EFFENDDATEHUM =  NAME + ".EffEndDateHum";
        public static final String COL_EFFTEMPDATEHUM =  NAME + ".EffTempDateHum";

        public static final String[] ARRAY = new String[] {
            COL_ID,COL_HUMIDITYSENSOR,COL_MANUFACTURER,COL_SERIALNUMBERSENSOR,COL_DATASAMPLINGSENSOR,COL_ACCURACY,COL_ASPIRATION,COL_HEIGHTDIFFSENSOR,COL_CALIDATE,COL_EFFDATEHUM,COL_ADDINFOHUMIDITY,COL_FOURID,COL_EFFSTARTDATEHUM,COL_EFFENDDATEHUM,COL_EFFTEMPDATEHUM
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final SITELOG_HUMIDITYSENSOR table  = new  SITELOG_HUMIDITYSENSOR();
    }



    public static class SITELOG_IDENTIFICATION extends Tables {
        public static final String NAME = "SiteLog_Identification";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_FOURID =  NAME + ".FourID";
        public static final String COL_SITENAME =  NAME + ".SiteName";
        public static final String COL_FOUR_CHARACTER_ID =  NAME + ".Four_character_id";
        public static final String COL_MONUMENTINSCRI =  NAME + ".MonumentInscri";
        public static final String COL_IERDOMES =  NAME + ".IERDOMES";
        public static final String COL_CDPNUM =  NAME + ".CDPNum";
        public static final String COL_DATEINSTALLED =  NAME + ".DateInstalled";

        public static final String[] ARRAY = new String[] {
            COL_FOURID,COL_SITENAME,COL_FOUR_CHARACTER_ID,COL_MONUMENTINSCRI,COL_IERDOMES,COL_CDPNUM,COL_DATEINSTALLED
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final SITELOG_IDENTIFICATION table  = new  SITELOG_IDENTIFICATION();
    }



    public static class SITELOG_IDENTIFICATIONGEOLOGIC extends Tables {
        public static final String NAME = "SiteLog_IdentificationGeologic";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_FOURID =  NAME + ".FourID";
        public static final String COL_GEOLOGICCHAR =  NAME + ".GeologicChar";
        public static final String COL_BEDROCKTYPE =  NAME + ".BedrockType";
        public static final String COL_BEDROCKCOND =  NAME + ".BedrockCond";
        public static final String COL_FRACTURESPACING =  NAME + ".FractureSpacing";
        public static final String COL_FAULTZONES =  NAME + ".FaultZones";
        public static final String COL_DISTANCE =  NAME + ".Distance";
        public static final String COL_ADDINFO1 =  NAME + ".AddInfo1";

        public static final String[] ARRAY = new String[] {
            COL_FOURID,COL_GEOLOGICCHAR,COL_BEDROCKTYPE,COL_BEDROCKCOND,COL_FRACTURESPACING,COL_FAULTZONES,COL_DISTANCE,COL_ADDINFO1
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final SITELOG_IDENTIFICATIONGEOLOGIC table  = new  SITELOG_IDENTIFICATIONGEOLOGIC();
    }



    public static class SITELOG_IDENTIFICATIONMONUMENT extends Tables {
        public static final String NAME = "SiteLog_IdentificationMonument";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_FOURID =  NAME + ".FourID";
        public static final String COL_MONUMENTDESCRIPT =  NAME + ".MonumentDescript";
        public static final String COL_MARKERDESCRIPT =  NAME + ".MarkerDescript";
        public static final String COL_HEIGHTMONU =  NAME + ".HeightMonu";
        public static final String COL_MONUFOUND =  NAME + ".MonuFound";
        public static final String COL_FOUNDDEPTH =  NAME + ".FoundDepth";

        public static final String[] ARRAY = new String[] {
            COL_FOURID,COL_MONUMENTDESCRIPT,COL_MARKERDESCRIPT,COL_HEIGHTMONU,COL_MONUFOUND,COL_FOUNDDEPTH
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final SITELOG_IDENTIFICATIONMONUMENT table  = new  SITELOG_IDENTIFICATIONMONUMENT();
    }



    public static class SITELOG_LOCALEPISODICEFFECTS extends Tables {
        public static final String NAME = "SiteLog_LocalEpisodicEffects";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_ID =  NAME + ".ID";
        public static final String COL_DATEEVENT =  NAME + ".DateEvent";
        public static final String COL_EVENT =  NAME + ".Event";
        public static final String COL_FOURID =  NAME + ".FourID";
        public static final String COL_EFFSTARTDATEEVENT =  NAME + ".EffStartDateEvent";
        public static final String COL_EFFENDDATEEVENT =  NAME + ".EffEndDateEvent";
        public static final String COL_EFFTEMPDATEEVENT =  NAME + ".EffTempDateEvent";

        public static final String[] ARRAY = new String[] {
            COL_ID,COL_DATEEVENT,COL_EVENT,COL_FOURID,COL_EFFSTARTDATEEVENT,COL_EFFENDDATEEVENT,COL_EFFTEMPDATEEVENT
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final SITELOG_LOCALEPISODICEFFECTS table  = new  SITELOG_LOCALEPISODICEFFECTS();
    }



    public static class SITELOG_LOCATION extends Tables {
        public static final String NAME = "SiteLog_Location";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_FOURID =  NAME + ".FourID";
        public static final String COL_CITY =  NAME + ".City";
        public static final String COL_STATE =  NAME + ".State";
        public static final String COL_COUNTRY =  NAME + ".Country";
        public static final String COL_TECTONIC =  NAME + ".Tectonic";
        public static final String COL_XCOOR =  NAME + ".XCoor";
        public static final String COL_YCOOR =  NAME + ".YCoor";
        public static final String COL_ZCOOR =  NAME + ".ZCoor";
        public static final String COL_LATITUDENORTH =  NAME + ".LatitudeNorth";
        public static final String COL_LONGITUDEEAST =  NAME + ".LongitudeEast";
        public static final String COL_ELEVATION =  NAME + ".Elevation";
        public static final String COL_ADDINFO2 =  NAME + ".AddInfo2";

        public static final String[] ARRAY = new String[] {
            COL_FOURID,COL_CITY,COL_STATE,COL_COUNTRY,COL_TECTONIC,COL_XCOOR,COL_YCOOR,COL_ZCOOR,COL_LATITUDENORTH,COL_LONGITUDEEAST,COL_ELEVATION,COL_ADDINFO2
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final SITELOG_LOCATION table  = new  SITELOG_LOCATION();
    }



    public static class SITELOG_MASTER extends Tables {
        public static final String NAME = "SiteLog_Master";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_FOURID =  NAME + ".FourID";
        public static final String COL_STATUSID =  NAME + ".StatusID";

        public static final String[] ARRAY = new String[] {
            COL_FOURID,COL_STATUSID
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final SITELOG_MASTER table  = new  SITELOG_MASTER();
    }



    public static class SITELOG_MASTER_STATUS extends Tables {
        public static final String NAME = "SiteLog_Master_Status";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_STATUSID =  NAME + ".StatusID";
        public static final String COL_STATUS =  NAME + ".Status";

        public static final String[] ARRAY = new String[] {
            COL_STATUSID,COL_STATUS
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final SITELOG_MASTER_STATUS table  = new  SITELOG_MASTER_STATUS();
    }



    public static class SITELOG_MULTIPATHSOURCES extends Tables {
        public static final String NAME = "SiteLog_MultipathSources";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_ID =  NAME + ".ID";
        public static final String COL_SOURCES =  NAME + ".Sources";
        public static final String COL_EFFDATEMULTI =  NAME + ".EffDateMulti";
        public static final String COL_ADDINFOMULTI =  NAME + ".AddinfoMulti";
        public static final String COL_FOURID =  NAME + ".FourID";
        public static final String COL_EFFSTARTDATEMULTI =  NAME + ".EffStartDateMulti";
        public static final String COL_EFFENDDATEMULTI =  NAME + ".EffEndDateMulti";
        public static final String COL_EFFTEMPDATEMULTI =  NAME + ".EffTempDateMulti";

        public static final String[] ARRAY = new String[] {
            COL_ID,COL_SOURCES,COL_EFFDATEMULTI,COL_ADDINFOMULTI,COL_FOURID,COL_EFFSTARTDATEMULTI,COL_EFFENDDATEMULTI,COL_EFFTEMPDATEMULTI
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final SITELOG_MULTIPATHSOURCES table  = new  SITELOG_MULTIPATHSOURCES();
    }



    public static class SITELOG_OPERATIONALCONTACT extends Tables {
        public static final String NAME = "SiteLog_OperationalContact";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_FOURID =  NAME + ".FourID";
        public static final String COL_NAMEAGENCY =  NAME + ".NameAgency";
        public static final String COL_PREABBR =  NAME + ".PreAbbr";
        public static final String COL_MAILINGADD =  NAME + ".MailingAdd";
        public static final String COL_NAME1 =  NAME + ".Name1";
        public static final String COL_TEL1 =  NAME + ".Tel1";
        public static final String COL_SECTEL1 =  NAME + ".Sectel1";
        public static final String COL_FAX1 =  NAME + ".Fax1";
        public static final String COL_EMAIL1 =  NAME + ".Email1";
        public static final String COL_NAME2 =  NAME + ".Name2";
        public static final String COL_TEL2 =  NAME + ".Tel2";
        public static final String COL_SECTEL2 =  NAME + ".Sectel2";
        public static final String COL_FAX2 =  NAME + ".Fax2";
        public static final String COL_EMAIL2 =  NAME + ".Email2";
        public static final String COL_ADDINFO11 =  NAME + ".AddInfo11";

        public static final String[] ARRAY = new String[] {
            COL_FOURID,COL_NAMEAGENCY,COL_PREABBR,COL_MAILINGADD,COL_NAME1,COL_TEL1,COL_SECTEL1,COL_FAX1,COL_EMAIL1,COL_NAME2,COL_TEL2,COL_SECTEL2,COL_FAX2,COL_EMAIL2,COL_ADDINFO11
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final SITELOG_OPERATIONALCONTACT table  = new  SITELOG_OPERATIONALCONTACT();
    }



    public static class SITELOG_OTHERINSTRUMENTATION extends Tables {
        public static final String NAME = "SiteLog_OtherInstrumentation";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_ID =  NAME + ".ID";
        public static final String COL_INSTRUMENTATION =  NAME + ".Instrumentation";
        public static final String COL_FOURID =  NAME + ".FourID";

        public static final String[] ARRAY = new String[] {
            COL_ID,COL_INSTRUMENTATION,COL_FOURID
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final SITELOG_OTHERINSTRUMENTATION table  = new  SITELOG_OTHERINSTRUMENTATION();
    }



    public static class SITELOG_PRESSURESENSOR extends Tables {
        public static final String NAME = "SiteLog_PressureSensor";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_ID =  NAME + ".ID";
        public static final String COL_PRESSSENSOR =  NAME + ".PressSensor";
        public static final String COL_MANUFACTUR =  NAME + ".ManuFactur";
        public static final String COL_SERIALNUMBERPRESSURE =  NAME + ".SerialNumberPressure";
        public static final String COL_DATASAMPLINGINTER =  NAME + ".DataSamplingInter";
        public static final String COL_ACCURACYHPA =  NAME + ".AccuracyhPa";
        public static final String COL_HEIGHTDIFFANTENNA =  NAME + ".HeightDiffAntenna";
        public static final String COL_CALIBRATIONDATE =  NAME + ".CalibrationDate";
        public static final String COL_EFFDATEPRESSURE =  NAME + ".EffDatePressure";
        public static final String COL_ADDINFOPRESSURE =  NAME + ".AddInfoPressure";
        public static final String COL_FOURID =  NAME + ".FourID";
        public static final String COL_EFFSTARTDATEPRESSURE =  NAME + ".EffStartDatePressure";
        public static final String COL_EFFENDDATEPRESSURE =  NAME + ".EffEndDatePressure";
        public static final String COL_EFFTEMPDATEPRESSURE =  NAME + ".EffTempDatePressure";

        public static final String[] ARRAY = new String[] {
            COL_ID,COL_PRESSSENSOR,COL_MANUFACTUR,COL_SERIALNUMBERPRESSURE,COL_DATASAMPLINGINTER,COL_ACCURACYHPA,COL_HEIGHTDIFFANTENNA,COL_CALIBRATIONDATE,COL_EFFDATEPRESSURE,COL_ADDINFOPRESSURE,COL_FOURID,COL_EFFSTARTDATEPRESSURE,COL_EFFENDDATEPRESSURE,COL_EFFTEMPDATEPRESSURE
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final SITELOG_PRESSURESENSOR table  = new  SITELOG_PRESSURESENSOR();
    }



    public static class SITELOG_RADIOINTERFERENCES extends Tables {
        public static final String NAME = "SiteLog_RadioInterferences";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_ID =  NAME + ".ID";
        public static final String COL_INTERFERENCES =  NAME + ".Interferences";
        public static final String COL_OBSERVEDDEGRA =  NAME + ".ObservedDegra";
        public static final String COL_EFFDATERADIO =  NAME + ".EffDateRadio";
        public static final String COL_ADDINFORADIO =  NAME + ".AddInfoRadio";
        public static final String COL_FOURID =  NAME + ".FourID";
        public static final String COL_EFFSTARTDATERADIO =  NAME + ".EffStartDateRadio";
        public static final String COL_EFFENDDATERADIO =  NAME + ".EffEndDateRadio";
        public static final String COL_EFFTEMPDATERADIO =  NAME + ".EffTempDateRadio";

        public static final String[] ARRAY = new String[] {
            COL_ID,COL_INTERFERENCES,COL_OBSERVEDDEGRA,COL_EFFDATERADIO,COL_ADDINFORADIO,COL_FOURID,COL_EFFSTARTDATERADIO,COL_EFFENDDATERADIO,COL_EFFTEMPDATERADIO
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final SITELOG_RADIOINTERFERENCES table  = new  SITELOG_RADIOINTERFERENCES();
    }



    public static class SITELOG_RECEIVER extends Tables {
        public static final String NAME = "SiteLog_Receiver";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_ID =  NAME + ".ID";
        public static final String COL_RECEIVERTYPE =  NAME + ".ReceiverType";
        public static final String COL_SATELLITESYSTEM =  NAME + ".SatelliteSystem";
        public static final String COL_SERIALNUMBERRECEIVER =  NAME + ".SerialNumberReceiver";
        public static final String COL_FIRMWAREV =  NAME + ".FirmWareV";
        public static final String COL_ELEVCUTTSETT =  NAME + ".ElevCuttSett";
        public static final String COL_DATEINSTALLEDRECEIVER =  NAME + ".DateInstalledReceiver";
        public static final String COL_DATEREMOVEDRECEIVER =  NAME + ".DateRemovedReceiver";
        public static final String COL_TEMPERATURESTAB =  NAME + ".TemperatureStab";
        public static final String COL_ADDINFORECEIVER =  NAME + ".AddInfoReceiver";
        public static final String COL_FOURID =  NAME + ".FourID";

        public static final String[] ARRAY = new String[] {
            COL_ID,COL_RECEIVERTYPE,COL_SATELLITESYSTEM,COL_SERIALNUMBERRECEIVER,COL_FIRMWAREV,COL_ELEVCUTTSETT,COL_DATEINSTALLEDRECEIVER,COL_DATEREMOVEDRECEIVER,COL_TEMPERATURESTAB,COL_ADDINFORECEIVER,COL_FOURID
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final SITELOG_RECEIVER table  = new  SITELOG_RECEIVER();
    }



    public static class SITELOG_RESPONSIBLEAGENCY extends Tables {
        public static final String NAME = "SiteLog_ResponsibleAgency";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_FOURID =  NAME + ".FourID";
        public static final String COL_AGENCYRESPONSIBLE =  NAME + ".AgencyResponsible";
        public static final String COL_PREABBRESPONSIBLE =  NAME + ".PreAbbResponsible";
        public static final String COL_MAILINADDRESPONSIBLE =  NAME + ".MailinAddResponsible";
        public static final String COL_CONTACTNAMERESPONSIBLE =  NAME + ".ContactNameResponsible";
        public static final String COL_TEL1RESPONSIBLE =  NAME + ".Tel1responsible";
        public static final String COL_TEL2RESPONSIBLE =  NAME + ".Tel2Responsible";
        public static final String COL_FAXRESPONSIBLE =  NAME + ".FaxResponsible";
        public static final String COL_EMAILRESPONSIBLE =  NAME + ".EmailResponsible";
        public static final String COL_CONTACT2RESPONSIBLE =  NAME + ".Contact2Responsible";
        public static final String COL_TELCONTACT1RESPONSIBLE =  NAME + ".TelContact1Responsible";
        public static final String COL_TELCONTACT2RESPONSIBLE =  NAME + ".TelContact2Responsible";
        public static final String COL_FAX2RESPONSIBLE =  NAME + ".Fax2Responsible";
        public static final String COL_EMAIL2RESPONSIBLE =  NAME + ".Email2Responsible";
        public static final String COL_ADDINFO12 =  NAME + ".AddInfo12";

        public static final String[] ARRAY = new String[] {
            COL_FOURID,COL_AGENCYRESPONSIBLE,COL_PREABBRESPONSIBLE,COL_MAILINADDRESPONSIBLE,COL_CONTACTNAMERESPONSIBLE,COL_TEL1RESPONSIBLE,COL_TEL2RESPONSIBLE,COL_FAXRESPONSIBLE,COL_EMAILRESPONSIBLE,COL_CONTACT2RESPONSIBLE,COL_TELCONTACT1RESPONSIBLE,COL_TELCONTACT2RESPONSIBLE,COL_FAX2RESPONSIBLE,COL_EMAIL2RESPONSIBLE,COL_ADDINFO12
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final SITELOG_RESPONSIBLEAGENCY table  = new  SITELOG_RESPONSIBLEAGENCY();
    }



    public static class SITELOG_SIGNALOBSTRUCTIONS extends Tables {
        public static final String NAME = "SiteLog_SignalObstructions";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_ID =  NAME + ".ID";
        public static final String COL_OBSTRUCTIONS =  NAME + ".Obstructions";
        public static final String COL_EFFDATESIGNAL =  NAME + ".EffDateSignal";
        public static final String COL_ADDINFOSIGNAL =  NAME + ".AddInfoSignal";
        public static final String COL_FOURID =  NAME + ".FourID";
        public static final String COL_EFFSTARTDATESIGNAL =  NAME + ".EffStartDateSignal";
        public static final String COL_EFFENDDATESIGNAL =  NAME + ".EffEndDateSignal";
        public static final String COL_EFFTEMPDATESIGNAL =  NAME + ".EffTempDateSignal";

        public static final String[] ARRAY = new String[] {
            COL_ID,COL_OBSTRUCTIONS,COL_EFFDATESIGNAL,COL_ADDINFOSIGNAL,COL_FOURID,COL_EFFSTARTDATESIGNAL,COL_EFFENDDATESIGNAL,COL_EFFTEMPDATESIGNAL
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final SITELOG_SIGNALOBSTRUCTIONS table  = new  SITELOG_SIGNALOBSTRUCTIONS();
    }



    public static class SITELOG_SURVEYEDLOCALTIES extends Tables {
        public static final String NAME = "SiteLog_SurveyedLocalTies";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_ID =  NAME + ".ID";
        public static final String COL_TIEDNAME =  NAME + ".TiedName";
        public static final String COL_TIEDUSAGE =  NAME + ".TiedUsage";
        public static final String COL_TIEDCDP =  NAME + ".TiedCDP";
        public static final String COL_TIEDDOMES =  NAME + ".TiedDOMES";
        public static final String COL_DX =  NAME + ".Dx";
        public static final String COL_DY =  NAME + ".Dy";
        public static final String COL_DZ =  NAME + ".Dz";
        public static final String COL_ACCURACYM =  NAME + ".Accuracym";
        public static final String COL_SURVEYMETHOD =  NAME + ".SurveyMethod";
        public static final String COL_DATEMEASURED =  NAME + ".DateMeasured";
        public static final String COL_ADDINFOSURVEYED =  NAME + ".AddInfoSurveyed";
        public static final String COL_FOURID =  NAME + ".FourID";

        public static final String[] ARRAY = new String[] {
            COL_ID,COL_TIEDNAME,COL_TIEDUSAGE,COL_TIEDCDP,COL_TIEDDOMES,COL_DX,COL_DY,COL_DZ,COL_ACCURACYM,COL_SURVEYMETHOD,COL_DATEMEASURED,COL_ADDINFOSURVEYED,COL_FOURID
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final SITELOG_SURVEYEDLOCALTIES table  = new  SITELOG_SURVEYEDLOCALTIES();
    }



    public static class SITELOG_TEMPERATURESENSOR extends Tables {
        public static final String NAME = "SiteLog_TemperatureSensor";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_ID =  NAME + ".ID";
        public static final String COL_TEMPSENSORMODEL =  NAME + ".TempSensorModel";
        public static final String COL_MANUFACT =  NAME + ".ManuFact";
        public static final String COL_SERIALNUMBERTEMP =  NAME + ".SerialNumberTemp";
        public static final String COL_DATASAMPLINGINTERVAL =  NAME + ".DataSamplingInterval";
        public static final String COL_ACCURACYDEGREES =  NAME + ".AccuracyDegrees";
        public static final String COL_ASPI =  NAME + ".Aspi";
        public static final String COL_HEIGHTDIFFAN =  NAME + ".HeightDiffAn";
        public static final String COL_CALI =  NAME + ".Cali";
        public static final String COL_EFFDATETEMP =  NAME + ".EffDateTemp";
        public static final String COL_ADDINFOTEMP =  NAME + ".AddInfoTemp";
        public static final String COL_FOURID =  NAME + ".FourID";
        public static final String COL_EFFSTARTDATETEMP =  NAME + ".EffStartDateTemp";
        public static final String COL_EFFENDDATETEMP =  NAME + ".EffEndDateTemp";
        public static final String COL_EFFTEMPDATETEMP =  NAME + ".EffTempDateTemp";

        public static final String[] ARRAY = new String[] {
            COL_ID,COL_TEMPSENSORMODEL,COL_MANUFACT,COL_SERIALNUMBERTEMP,COL_DATASAMPLINGINTERVAL,COL_ACCURACYDEGREES,COL_ASPI,COL_HEIGHTDIFFAN,COL_CALI,COL_EFFDATETEMP,COL_ADDINFOTEMP,COL_FOURID,COL_EFFSTARTDATETEMP,COL_EFFENDDATETEMP,COL_EFFTEMPDATETEMP
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final SITELOG_TEMPERATURESENSOR table  = new  SITELOG_TEMPERATURESENSOR();
    }



    public static class SITELOG_WATERVAPORRADIOMETER extends Tables {
        public static final String NAME = "SiteLog_WaterVaporRadiometer";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_ID =  NAME + ".ID";
        public static final String COL_WATERVAPOR =  NAME + ".WaterVapor";
        public static final String COL_MANU =  NAME + ".Manu";
        public static final String COL_SERIALNUMBERWATER =  NAME + ".SerialNumberWater";
        public static final String COL_DISTANCETOANT =  NAME + ".DistanceToAnt";
        public static final String COL_HEIGHT =  NAME + ".Height";
        public static final String COL_CALIB =  NAME + ".Calib";
        public static final String COL_EFFDATEWATER =  NAME + ".EffDateWater";
        public static final String COL_ADDINFOWATER =  NAME + ".AddInfoWater";
        public static final String COL_FOURID =  NAME + ".FourID";
        public static final String COL_EFFSTARTDATEWATER =  NAME + ".EffStartDateWater";
        public static final String COL_EFFENDDATEWATER =  NAME + ".EffEndDateWater";
        public static final String COL_EFFTEMPDATEWATER =  NAME + ".EffTempDateWater";

        public static final String[] ARRAY = new String[] {
            COL_ID,COL_WATERVAPOR,COL_MANU,COL_SERIALNUMBERWATER,COL_DISTANCETOANT,COL_HEIGHT,COL_CALIB,COL_EFFDATEWATER,COL_ADDINFOWATER,COL_FOURID,COL_EFFSTARTDATEWATER,COL_EFFENDDATEWATER,COL_EFFTEMPDATEWATER
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final SITELOG_WATERVAPORRADIOMETER table  = new  SITELOG_WATERVAPORRADIOMETER();
    }



    public static class STATION_IDENTIFICATION extends Tables {
        public static final String NAME = "Station_Identification";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_MARKERNAME =  NAME + ".MarkerName";
        public static final String COL_MARKERNUMBER =  NAME + ".MarkerNumber";
        public static final String COL_LATITUDE =  NAME + ".Latitude";
        public static final String COL_LONGITUDE =  NAME + ".Longitude";
        public static final String COL_CITY =  NAME + ".City";
        public static final String COL_COUNTRY =  NAME + ".Country";
        public static final String COL_PROPOSITIONDATE =  NAME + ".PropositionDate";
        public static final String COL_COMMITMENTLETTER =  NAME + ".CommitmentLetter";
        public static final String COL_CONSISTENT_RINEX_FILES =  NAME + ".Consistent_RINEX_files";
        public static final String COL_INDIVIDUALCALIBRATION =  NAME + ".IndividualCalibration";
        public static final String COL_DATAQUALITY =  NAME + ".DataQuality";
        public static final String COL_DENSIFICATIONSITE =  NAME + ".DensificationSite";
        public static final String COL_COLLOCATEDINSTRUMENT =  NAME + ".CollocatedInstrument";
        public static final String COL_INTERESTEDANALYSISCENTRES =  NAME + ".InterestedAnalysisCentres";
        public static final String COL_HOURLY_DATA =  NAME + ".Hourly_data";
        public static final String COL_ECGN_DATA =  NAME + ".ECGN_data";
        public static final String COL_MAINDATACENTRE =  NAME + ".MainDatacentre";
        public static final String COL_TIDEGAUGE =  NAME + ".Tidegauge";
        public static final String COL_REMARK =  NAME + ".Remark";

        public static final String[] ARRAY = new String[] {
            COL_MARKERNAME,COL_MARKERNUMBER,COL_LATITUDE,COL_LONGITUDE,COL_CITY,COL_COUNTRY,COL_PROPOSITIONDATE,COL_COMMITMENTLETTER,COL_CONSISTENT_RINEX_FILES,COL_INDIVIDUALCALIBRATION,COL_DATAQUALITY,COL_DENSIFICATIONSITE,COL_COLLOCATEDINSTRUMENT,COL_INTERESTEDANALYSISCENTRES,COL_HOURLY_DATA,COL_ECGN_DATA,COL_MAINDATACENTRE,COL_TIDEGAUGE,COL_REMARK
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final STATION_IDENTIFICATION table  = new  STATION_IDENTIFICATION();
    }



    public static class STATION_STATUS extends Tables {
        public static final String NAME = "Station_Status";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_MARKERNAME =  NAME + ".MarkerName";
        public static final String COL_STATUS =  NAME + ".Status";
        public static final String COL_BEGIN =  NAME + ".Begin";
        public static final String COL_END =  NAME + ".End";

        public static final String[] ARRAY = new String[] {
            COL_MARKERNAME,COL_STATUS,COL_BEGIN,COL_END
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final STATION_STATUS table  = new  STATION_STATUS();
    }



    public static class TECTONICPLATES extends Tables {
        public static final String NAME = "TectonicPlates";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_NAME =  NAME + ".Name";

        public static final String[] ARRAY = new String[] {
            COL_NAME
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final TECTONICPLATES table  = new  TECTONICPLATES();
    }



    public static class UNAV_QC_DATA extends Tables {
        public static final String NAME = "UNAV_QC_Data";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_FOURID =  NAME + ".FourID";
        public static final String COL_FILE_NAME =  NAME + ".file_name";
        public static final String COL_FILE_SIZE =  NAME + ".file_size";
        public static final String COL_START_TIME =  NAME + ".start_time";
        public static final String COL_FILE_TYPE =  NAME + ".file_type";
        public static final String COL_FILE_ID =  NAME + ".file_id";
        public static final String COL_POSSIBLE_OBS_GT_CUTOFF =  NAME + ".possible_obs_gt_cutoff";
        public static final String COL_COMPLETE_OBS_GT_CUTOFF =  NAME + ".complete_obs_gt_cutoff";
        public static final String COL_MP1_RMS =  NAME + ".mp1_rms";
        public static final String COL_MP2_RMS =  NAME + ".mp2_rms";
        public static final String COL_IOD_OR_MP_SLIPS =  NAME + ".iod_or_mp_slips";
        public static final String COL_POSSIBLE_OBS_EPOCHS =  NAME + ".possible_obs_epochs";
        public static final String COL_EPOCHS_W_OBS =  NAME + ".epochs_w_obs";
        public static final String COL_STATION_ID =  NAME + ".station_id";
        public static final String COL_MONUMENT_ID =  NAME + ".monument_id";
        public static final String COL_START_DAY =  NAME + ".start_day";

        public static final String[] ARRAY = new String[] {
            COL_FOURID,COL_FILE_NAME,COL_FILE_SIZE,COL_START_TIME,COL_FILE_TYPE,COL_FILE_ID,COL_POSSIBLE_OBS_GT_CUTOFF,COL_COMPLETE_OBS_GT_CUTOFF,COL_MP1_RMS,COL_MP2_RMS,COL_IOD_OR_MP_SLIPS,COL_POSSIBLE_OBS_EPOCHS,COL_EPOCHS_W_OBS,COL_STATION_ID,COL_MONUMENT_ID,COL_START_DAY
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final UNAV_QC_DATA table  = new  UNAV_QC_DATA();
    }



    public static class AUDITLOG extends Tables {
        public static final String NAME = "auditLog";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_TABLENAME =  NAME + ".tableName";
        public static final String COL_ROWPK1 =  NAME + ".rowPK1";
        public static final String COL_ROWPK2 =  NAME + ".rowPK2";
        public static final String COL_FIELDNAME =  NAME + ".fieldName";
        public static final String COL_OLD_VALUE =  NAME + ".old_value";
        public static final String COL_NEW_VALUE =  NAME + ".new_value";
        public static final String COL_TS =  NAME + ".ts";
        public static final String COL_ACTIVITY =  NAME + ".activity";

        public static final String[] ARRAY = new String[] {
            COL_TABLENAME,COL_ROWPK1,COL_ROWPK2,COL_FIELDNAME,COL_OLD_VALUE,COL_NEW_VALUE,COL_TS,COL_ACTIVITY
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final AUDITLOG table  = new  AUDITLOG();
    }



    public static class V_AUDITLOG extends Tables {
        public static final String NAME = "v_auditLog";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_TABLENAME =  NAME + ".tableName";
        public static final String COL_ROWPK1 =  NAME + ".rowPK1";
        public static final String COL_ROWPK2 =  NAME + ".rowPK2";
        public static final String COL_FIELDNAME =  NAME + ".fieldName";
        public static final String COL_OLD_VALUE =  NAME + ".old_value";
        public static final String COL_NEW_VALUE =  NAME + ".new_value";
        public static final String COL_TS =  NAME + ".ts";
        public static final String COL_ACTIVITY =  NAME + ".activity";
        public static final String COL_FORMFIELDLABEL =  NAME + ".FormFieldLabel";

        public static final String[] ARRAY = new String[] {
            COL_TABLENAME,COL_ROWPK1,COL_ROWPK2,COL_FIELDNAME,COL_OLD_VALUE,COL_NEW_VALUE,COL_TS,COL_ACTIVITY,COL_FORMFIELDLABEL
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final V_AUDITLOG table  = new  V_AUDITLOG();
    }



}
