/**Generated by running: java org.unavco.projects.gsac.repository.UnavcoGsacDatabaseManager**/

package org.prototype.gsac.database;

import org.ramadda.sql.SqlUtil;

public abstract class Tables {
    public abstract String getName();
    public abstract String getColumns();


    public static class ACCESS_PERMISSION extends Tables {
        public static final String NAME = "access_permission";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_ACCESS_PERMISSION_ID =  NAME + ".access_permission_id";
        public static final String COL_ACCESS_PERMISSION_DESCRIPTION =  NAME + ".access_permission_description";

        public static final String[] ARRAY = new String[] {
            COL_ACCESS_PERMISSION_ID,COL_ACCESS_PERMISSION_DESCRIPTION
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final ACCESS_PERMISSION table  = new  ACCESS_PERMISSION();
    }



    public static class AGENCY extends Tables {
        public static final String NAME = "agency";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_AGENCY_ID =  NAME + ".agency_id";
        public static final String COL_AGENCY_NAME =  NAME + ".agency_name";
        public static final String COL_MAILING_ADDRESS =  NAME + ".mailing_address";
        public static final String COL_AGENCY_URL =  NAME + ".agency_url";
        public static final String COL_PRIME_CONTACT_NAME =  NAME + ".prime_contact_name";
        public static final String COL_PRIME_TELEPHONE =  NAME + ".prime_telephone";
        public static final String COL_PRIME_FAX =  NAME + ".prime_fax";
        public static final String COL_PRIME_EMAIL =  NAME + ".prime_email";

        public static final String[] ARRAY = new String[] {
            COL_AGENCY_ID,COL_AGENCY_NAME,COL_MAILING_ADDRESS,COL_AGENCY_URL,COL_PRIME_CONTACT_NAME,COL_PRIME_TELEPHONE,COL_PRIME_FAX,COL_PRIME_EMAIL
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final AGENCY table  = new  AGENCY();
    }



    public static class ANTENNA_SESSION extends Tables {
        public static final String NAME = "antenna_session";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_ANTENNA_SESSION_ID =  NAME + ".antenna_session_id";
        public static final String COL_STATION_ID =  NAME + ".station_id";
        public static final String COL_ANTENNA_TYPE_ID =  NAME + ".antenna_type_id";
        public static final String COL_ANTENNA_SERIAL_NUMBER =  NAME + ".antenna_serial_number";
        public static final String COL_ANTENNA_INSTALLED_DATE =  NAME + ".antenna_installed_date";
        public static final String COL_ANTENNA_REMOVED_DATE =  NAME + ".antenna_removed_date";
        public static final String COL_ANTENNA_OFFSET_UP =  NAME + ".antenna_offset_up";
        public static final String COL_ANTENNA_OFFSET_NORTH =  NAME + ".antenna_offset_north";
        public static final String COL_ANTENNA_OFFSET_EAST =  NAME + ".antenna_offset_east";
        public static final String COL_ANTENNA_HTCOD =  NAME + ".antenna_HtCod";
        public static final String COL_RADOME_TYPE_ID =  NAME + ".radome_type_id";

        public static final String[] ARRAY = new String[] {
            COL_ANTENNA_SESSION_ID,COL_STATION_ID,COL_ANTENNA_TYPE_ID,COL_ANTENNA_SERIAL_NUMBER,COL_ANTENNA_INSTALLED_DATE,COL_ANTENNA_REMOVED_DATE,COL_ANTENNA_OFFSET_UP,COL_ANTENNA_OFFSET_NORTH,COL_ANTENNA_OFFSET_EAST,COL_ANTENNA_HTCOD,COL_RADOME_TYPE_ID
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final ANTENNA_SESSION table  = new  ANTENNA_SESSION();
    }



    public static class ANTENNA_TYPE extends Tables {
        public static final String NAME = "antenna_type";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_ANTENNA_TYPE_ID =  NAME + ".antenna_type_id";
        public static final String COL_ANTENNA_TYPE_NAME =  NAME + ".antenna_type_name";
        public static final String COL_IGS_DEFINED =  NAME + ".igs_defined";

        public static final String[] ARRAY = new String[] {
            COL_ANTENNA_TYPE_ID,COL_ANTENNA_TYPE_NAME,COL_IGS_DEFINED
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final ANTENNA_TYPE table  = new  ANTENNA_TYPE();
    }



    public static class COUNTRY extends Tables {
        public static final String NAME = "country";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_COUNTRY_ID =  NAME + ".country_id";
        public static final String COL_COUNTRY_NAME =  NAME + ".country_name";

        public static final String[] ARRAY = new String[] {
            COL_COUNTRY_ID,COL_COUNTRY_NAME
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final COUNTRY table  = new  COUNTRY();
    }



    public static class FILE_TYPE extends Tables {
        public static final String NAME = "file_type";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_FILE_TYPE_ID =  NAME + ".file_type_id";
        public static final String COL_FILE_TYPE_NAME =  NAME + ".file_type_name";

        public static final String[] ARRAY = new String[] {
            COL_FILE_TYPE_ID,COL_FILE_TYPE_NAME
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final FILE_TYPE table  = new  FILE_TYPE();
    }



    public static class GNSS_DATA_FILE extends Tables {
        public static final String NAME = "gnss_data_file";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_FILE_ID =  NAME + ".file_id";
        public static final String COL_STATION_ID =  NAME + ".station_id";
        public static final String COL_FILE_TYPE_ID =  NAME + ".file_type_id";
        public static final String COL_DATA_START_TIME =  NAME + ".data_start_time";
        public static final String COL_DATA_STOP_TIME =  NAME + ".data_stop_time";
        public static final String COL_PUBLISHED_DATE =  NAME + ".published_date";
        public static final String COL_REVISION_TIME =  NAME + ".revision_time";
        public static final String COL_FILE_SIZE =  NAME + ".file_size";
        public static final String COL_FILE_MD5 =  NAME + ".file_MD5";
        public static final String COL_FILE_URL =  NAME + ".file_url";
        public static final String COL_FILE_URL_PROTOCOL =  NAME + ".file_url_protocol";
        public static final String COL_FILE_URL_IP_DOMAIN =  NAME + ".file_url_ip_domain";
        public static final String COL_FILE_URL_FOLDERS =  NAME + ".file_url_folders";
        public static final String COL_FILE_URL_FILENAME =  NAME + ".file_url_filename";
        public static final String COL_FILE_SAMPLE_INTERVAL =  NAME + ".file_sample_interval";
        public static final String COL_ACCESS_PERMISSION_ID =  NAME + ".access_permission_id";
        public static final String COL_EMBARGO_AFTER_DATE =  NAME + ".embargo_after_date";
        public static final String COL_EMBARGO_DURATION_HOURS =  NAME + ".embargo_duration_hours";

        public static final String[] ARRAY = new String[] {
            COL_FILE_ID,COL_STATION_ID,COL_FILE_TYPE_ID,COL_DATA_START_TIME,COL_DATA_STOP_TIME,COL_PUBLISHED_DATE,COL_REVISION_TIME,COL_FILE_SIZE,COL_FILE_MD5,COL_FILE_URL,COL_FILE_URL_PROTOCOL,COL_FILE_URL_IP_DOMAIN,COL_FILE_URL_FOLDERS,COL_FILE_URL_FILENAME,COL_FILE_SAMPLE_INTERVAL,COL_ACCESS_PERMISSION_ID,COL_EMBARGO_AFTER_DATE,COL_EMBARGO_DURATION_HOURS
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final GNSS_DATA_FILE table  = new  GNSS_DATA_FILE();
    }



    public static class MONUMENT_DESCRIPTION extends Tables {
        public static final String NAME = "monument_description";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_MONUMENT_DESCRIPTION_ID =  NAME + ".monument_description_id";
        public static final String COL_MONUMENT_DESCRIPTION =  NAME + ".monument_description";

        public static final String[] ARRAY = new String[] {
            COL_MONUMENT_DESCRIPTION_ID,COL_MONUMENT_DESCRIPTION
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final MONUMENT_DESCRIPTION table  = new  MONUMENT_DESCRIPTION();
    }



    public static class PROVINCE_REGION_STATE extends Tables {
        public static final String NAME = "province_region_state";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_PROVINCE_REGION_STATE_ID =  NAME + ".province_region_state_id";
        public static final String COL_PROVINCE_REGION_STATE_NAME =  NAME + ".province_region_state_name";

        public static final String[] ARRAY = new String[] {
            COL_PROVINCE_REGION_STATE_ID,COL_PROVINCE_REGION_STATE_NAME
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final PROVINCE_REGION_STATE table  = new  PROVINCE_REGION_STATE();
    }



    public static class RADOME_TYPE extends Tables {
        public static final String NAME = "radome_type";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_RADOME_TYPE_ID =  NAME + ".radome_type_id";
        public static final String COL_RADOME_TYPE_NAME =  NAME + ".radome_type_name";
        public static final String COL_IGS_DEFINED =  NAME + ".igs_defined";
        public static final String COL_DESCRIPTION_ENGLISH =  NAME + ".description_English";
        public static final String COL_DESCRIPTION_RENAG =  NAME + ".description_RENAG";

        public static final String[] ARRAY = new String[] {
            COL_RADOME_TYPE_ID,COL_RADOME_TYPE_NAME,COL_IGS_DEFINED,COL_DESCRIPTION_ENGLISH,COL_DESCRIPTION_RENAG
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final RADOME_TYPE table  = new  RADOME_TYPE();
    }



    public static class RECEIVER_FIRMWARE_VERSION extends Tables {
        public static final String NAME = "receiver_firmware_version";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_RECEIVER_FIRMWARE_VERSION_ID =  NAME + ".receiver_firmware_version_id";
        public static final String COL_RECEIVER_FIRMWARE_VERSION_NAME =  NAME + ".receiver_firmware_version_name";
        public static final String COL_SWVER =  NAME + ".SwVer";

        public static final String[] ARRAY = new String[] {
            COL_RECEIVER_FIRMWARE_VERSION_ID,COL_RECEIVER_FIRMWARE_VERSION_NAME,COL_SWVER
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final RECEIVER_FIRMWARE_VERSION table  = new  RECEIVER_FIRMWARE_VERSION();
    }



    public static class RECEIVER_SESSION extends Tables {
        public static final String NAME = "receiver_session";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_RECEIVER_SESSION_ID =  NAME + ".receiver_session_id";
        public static final String COL_STATION_ID =  NAME + ".station_id";
        public static final String COL_RECEIVER_TYPE_ID =  NAME + ".receiver_type_id";
        public static final String COL_RECEIVER_FIRMWARE_VERSION_ID =  NAME + ".receiver_firmware_version_id";
        public static final String COL_RECEIVER_SERIAL_NUMBER =  NAME + ".receiver_serial_number";
        public static final String COL_RECEIVER_INSTALLED_DATE =  NAME + ".receiver_installed_date";
        public static final String COL_RECEIVER_REMOVED_DATE =  NAME + ".receiver_removed_date";
        public static final String COL_RECEIVER_SAMPLE_INTERVAL =  NAME + ".receiver_sample_interval";
        public static final String COL_SATELLITE_SYSTEM =  NAME + ".satellite_system";

        public static final String[] ARRAY = new String[] {
            COL_RECEIVER_SESSION_ID,COL_STATION_ID,COL_RECEIVER_TYPE_ID,COL_RECEIVER_FIRMWARE_VERSION_ID,COL_RECEIVER_SERIAL_NUMBER,COL_RECEIVER_INSTALLED_DATE,COL_RECEIVER_REMOVED_DATE,COL_RECEIVER_SAMPLE_INTERVAL,COL_SATELLITE_SYSTEM
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final RECEIVER_SESSION table  = new  RECEIVER_SESSION();
    }



    public static class RECEIVER_TYPE extends Tables {
        public static final String NAME = "receiver_type";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_RECEIVER_TYPE_ID =  NAME + ".receiver_type_id";
        public static final String COL_RECEIVER_TYPE_NAME =  NAME + ".receiver_type_name";
        public static final String COL_IGS_DEFINED =  NAME + ".igs_defined";

        public static final String[] ARRAY = new String[] {
            COL_RECEIVER_TYPE_ID,COL_RECEIVER_TYPE_NAME,COL_IGS_DEFINED
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final RECEIVER_TYPE table  = new  RECEIVER_TYPE();
    }



    public static class STATION extends Tables {
        public static final String NAME = "station";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_STATION_ID =  NAME + ".station_id";
        public static final String COL_CODE_4CHAR_ID =  NAME + ".code_4char_ID";
        public static final String COL_STATION_NAME =  NAME + ".station_name";
        public static final String COL_LATITUDE_NORTH =  NAME + ".latitude_north";
        public static final String COL_LONGITUDE_EAST =  NAME + ".longitude_east";
        public static final String COL_ELLIPSOIDAL_HEIGHT =  NAME + ".ellipsoidal_height";
        public static final String COL_STATION_INSTALLED_DATE =  NAME + ".station_installed_date";
        public static final String COL_STATION_REMOVED_DATE =  NAME + ".station_removed_date";
        public static final String COL_STATION_STYLE_ID =  NAME + ".station_style_id";
        public static final String COL_STATION_STATUS_ID =  NAME + ".station_status_id";
        public static final String COL_ACCESS_PERMISSION_ID =  NAME + ".access_permission_id";
        public static final String COL_MONUMENT_DESCRIPTION_ID =  NAME + ".monument_description_id";
        public static final String COL_COUNTRY_ID =  NAME + ".country_id";
        public static final String COL_PROVINCE_REGION_STATE_ID =  NAME + ".province_region_state_id";
        public static final String COL_CITY =  NAME + ".city";
        public static final String COL_X =  NAME + ".x";
        public static final String COL_Y =  NAME + ".y";
        public static final String COL_Z =  NAME + ".z";
        public static final String COL_IERS_DOMES =  NAME + ".iers_domes";
        public static final String COL_STATION_PHOTO_URL =  NAME + ".station_photo_URL";
        public static final String COL_TIME_SERIES_IMAGE_URL =  NAME + ".time_series_image_URL";
        public static final String COL_AGENCY_ID =  NAME + ".agency_id";
        public static final String COL_NETWORKS =  NAME + ".networks";
        public static final String COL_EMBARGO_DURATION_HOURS =  NAME + ".embargo_duration_hours";
        public static final String COL_EMBARGO_AFTER_DATE =  NAME + ".embargo_after_date";

        public static final String[] ARRAY = new String[] {
            COL_STATION_ID,COL_CODE_4CHAR_ID,COL_STATION_NAME,COL_LATITUDE_NORTH,COL_LONGITUDE_EAST,COL_ELLIPSOIDAL_HEIGHT,COL_STATION_INSTALLED_DATE,COL_STATION_REMOVED_DATE,COL_STATION_STYLE_ID,COL_STATION_STATUS_ID,COL_ACCESS_PERMISSION_ID,COL_MONUMENT_DESCRIPTION_ID,COL_COUNTRY_ID,COL_PROVINCE_REGION_STATE_ID,COL_CITY,COL_X,COL_Y,COL_Z,COL_IERS_DOMES,COL_STATION_PHOTO_URL,COL_TIME_SERIES_IMAGE_URL,COL_AGENCY_ID,COL_NETWORKS,COL_EMBARGO_DURATION_HOURS,COL_EMBARGO_AFTER_DATE
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final STATION table  = new  STATION();
    }



    public static class STATION_STATUS extends Tables {
        public static final String NAME = "station_status";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_STATION_STATUS_ID =  NAME + ".station_status_id";
        public static final String COL_STATION_STATUS_DESCRIPTION =  NAME + ".station_status_description";

        public static final String[] ARRAY = new String[] {
            COL_STATION_STATUS_ID,COL_STATION_STATUS_DESCRIPTION
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final STATION_STATUS table  = new  STATION_STATUS();
    }



    public static class STATION_STYLE extends Tables {
        public static final String NAME = "station_style";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_STATION_STYLE_ID =  NAME + ".station_style_id";
        public static final String COL_STATION_STYLE_NAME =  NAME + ".station_style_name";

        public static final String[] ARRAY = new String[] {
            COL_STATION_STYLE_ID,COL_STATION_STYLE_NAME
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final STATION_STYLE table  = new  STATION_STYLE();
    }



}
