/**Generated by running: java org.unavco.projects.gsac.repository.UnavcoGsacDatabaseManager**/

package org.ring.gsac.database;

import ucar.unidata.sql.SqlUtil;

//J-
public abstract class Tables {
    public abstract String getName();
    public abstract String getColumns();


    public static class ACTIONS extends Tables {
        public static final String NAME = "actions";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_ID_ACTION =  NAME + ".id_action";
        public static final String COL_NAME =  NAME + ".name";
        public static final String COL_DESCRIPTION =  NAME + ".description";

        public static final String[] ARRAY = new String[] {
            COL_ID_ACTION,COL_NAME,COL_DESCRIPTION
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final ACTIONS table  = new  ACTIONS();
    }



    public static class AGENCY extends Tables {
        public static final String NAME = "agency";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_ID =  NAME + ".id";
        public static final String COL_AGENCY =  NAME + ".agency";
        public static final String COL_PREFERRED_ABBREVATION =  NAME + ".preferred_abbrevation";
        public static final String COL_MAILING_ADDRESS =  NAME + ".mailing_address";
        public static final String COL_PRIMARY_CONTACT_NAME =  NAME + ".primary_contact_name";
        public static final String COL_PRIMARY_CONTACT_TELEPHONE =  NAME + ".primary_contact_telephone";
        public static final String COL_PRIMARY_CONTACT_MOBILE =  NAME + ".primary_contact_mobile";
        public static final String COL_PRIMARY_CONTACT_FAX =  NAME + ".primary_contact_fax";
        public static final String COL_PRIMARY_CONTACT_EMAIL =  NAME + ".primary_contact_email";
        public static final String COL_SECONDARY_CONTACT_NAME =  NAME + ".secondary_contact_name";
        public static final String COL_SECONDARY_CONTACT_TELEPHONE =  NAME + ".secondary_contact_telephone";
        public static final String COL_SECONDARY_CONTACT_MOBILE =  NAME + ".secondary_contact_mobile";
        public static final String COL_SECONDARY_CONTACT_FAX =  NAME + ".secondary_contact_fax";
        public static final String COL_SECONDARY_CONTACT_EMAIL =  NAME + ".secondary_contact_email";
        public static final String COL_ADDITIONAL_INFORMATION =  NAME + ".additional_information";

        public static final String[] ARRAY = new String[] {
            COL_ID,COL_AGENCY,COL_PREFERRED_ABBREVATION,COL_MAILING_ADDRESS,COL_PRIMARY_CONTACT_NAME,COL_PRIMARY_CONTACT_TELEPHONE,COL_PRIMARY_CONTACT_MOBILE,COL_PRIMARY_CONTACT_FAX,COL_PRIMARY_CONTACT_EMAIL,COL_SECONDARY_CONTACT_NAME,COL_SECONDARY_CONTACT_TELEPHONE,COL_SECONDARY_CONTACT_MOBILE,COL_SECONDARY_CONTACT_FAX,COL_SECONDARY_CONTACT_EMAIL,COL_ADDITIONAL_INFORMATION
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final AGENCY table  = new  AGENCY();
    }



    public static class AGENZIE extends Tables {
        public static final String NAME = "agenzie";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_ID_AGENZIA =  NAME + ".id_agenzia";
        public static final String COL_AGENZIA =  NAME + ".agenzia";
        public static final String COL_PREFERRED_ABBREVATION =  NAME + ".preferred_abbrevation";
        public static final String COL_MAILING_ADDRESS =  NAME + ".mailing_address";
        public static final String COL_PRIMARY_CONTACT_NAME =  NAME + ".primary_contact_name";
        public static final String COL_PRIMARY_CONTACT_TELEPHONE =  NAME + ".primary_contact_telephone";
        public static final String COL_PRIMARY_CONTACT_MOBILE =  NAME + ".primary_contact_mobile";
        public static final String COL_PRIMARY_CONTACT_FAX =  NAME + ".primary_contact_fax";
        public static final String COL_PRIMARY_CONTACT_EMAIL =  NAME + ".primary_contact_email";
        public static final String COL_SECONDARY_CONTACT_NAME =  NAME + ".secondary_contact_name";
        public static final String COL_SECONDARY_CONTACT_TELEPHONE =  NAME + ".secondary_contact_telephone";
        public static final String COL_SECONDARY_CONTACT_MOBILE =  NAME + ".secondary_contact_mobile";
        public static final String COL_SECONDARY_CONTACT_FAX =  NAME + ".secondary_contact_fax";
        public static final String COL_SECONDARY_CONTACT_EMAIL =  NAME + ".secondary_contact_email";
        public static final String COL_ADDITIONAL_INFORMATION =  NAME + ".additional_information";

        public static final String[] ARRAY = new String[] {
            COL_ID_AGENZIA,COL_AGENZIA,COL_PREFERRED_ABBREVATION,COL_MAILING_ADDRESS,COL_PRIMARY_CONTACT_NAME,COL_PRIMARY_CONTACT_TELEPHONE,COL_PRIMARY_CONTACT_MOBILE,COL_PRIMARY_CONTACT_FAX,COL_PRIMARY_CONTACT_EMAIL,COL_SECONDARY_CONTACT_NAME,COL_SECONDARY_CONTACT_TELEPHONE,COL_SECONDARY_CONTACT_MOBILE,COL_SECONDARY_CONTACT_FAX,COL_SECONDARY_CONTACT_EMAIL,COL_ADDITIONAL_INFORMATION
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final AGENZIE table  = new  AGENZIE();
    }



    public static class DATA_CENTERS extends Tables {
        public static final String NAME = "data_centers";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_ID_DATA_CENTER =  NAME + ".id_data_center";
        public static final String COL_PRIMARY_DATA_CENTER =  NAME + ".primary_data_center";
        public static final String COL_SECONDARY_DATA_CENTER =  NAME + ".secondary_data_center";
        public static final String COL_URL =  NAME + ".url";
        public static final String COL_SITE_MAP =  NAME + ".site_map";
        public static final String COL_SITE_DIAGRAM =  NAME + ".site_diagram";
        public static final String COL_HORIZON_MASK =  NAME + ".horizon_mask";
        public static final String COL_MONUMENT_DESCRIPTION =  NAME + ".monument_description";
        public static final String COL_SITE_PICTURES =  NAME + ".site_pictures";
        public static final String COL_ADDITIONAL_INFORMATION =  NAME + ".additional_information";

        public static final String[] ARRAY = new String[] {
            COL_ID_DATA_CENTER,COL_PRIMARY_DATA_CENTER,COL_SECONDARY_DATA_CENTER,COL_URL,COL_SITE_MAP,COL_SITE_DIAGRAM,COL_HORIZON_MASK,COL_MONUMENT_DESCRIPTION,COL_SITE_PICTURES,COL_ADDITIONAL_INFORMATION
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final DATA_CENTERS table  = new  DATA_CENTERS();
    }



    public static class EVENTS extends Tables {
        public static final String NAME = "events";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_ID_EVENTO =  NAME + ".id_evento";
        public static final String COL_ID_SITO =  NAME + ".id_sito";
        public static final String COL_DATE_START =  NAME + ".date_start";
        public static final String COL_DATE_END =  NAME + ".date_end";
        public static final String COL_EVENT_DESCRIPTION =  NAME + ".event_description";

        public static final String[] ARRAY = new String[] {
            COL_ID_EVENTO,COL_ID_SITO,COL_DATE_START,COL_DATE_END,COL_EVENT_DESCRIPTION
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final EVENTS table  = new  EVENTS();
    }



    public static class MANUTENZIONE_ALTRI_STRUMENTI extends Tables {
        public static final String NAME = "manutenzione_altri_strumenti";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_ID =  NAME + ".id";
        public static final String COL_ID_SITO =  NAME + ".id_sito";
        public static final String COL_DATE_INSTALLED =  NAME + ".date_installed";
        public static final String COL_DATE_REMOVED =  NAME + ".date_removed";
        public static final String COL_NOTES =  NAME + ".notes";

        public static final String[] ARRAY = new String[] {
            COL_ID,COL_ID_SITO,COL_DATE_INSTALLED,COL_DATE_REMOVED,COL_NOTES
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final MANUTENZIONE_ALTRI_STRUMENTI table  = new  MANUTENZIONE_ALTRI_STRUMENTI();
    }



    public static class MANUTENZIONE_ANTENNA extends Tables {
        public static final String NAME = "manutenzione_antenna";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_ID_MANUTENZIONE =  NAME + ".id_manutenzione";
        public static final String COL_ID_SITO =  NAME + ".id_sito";
        public static final String COL_ID_ANTENNA =  NAME + ".id_antenna";
        public static final String COL_DATE_INSTALLED =  NAME + ".date_installed";
        public static final String COL_DATE_REMOVED =  NAME + ".date_removed";
        public static final String COL_REFERENCE_POINT =  NAME + ".reference_point";
        public static final String COL_MARKER_ARP_UP =  NAME + ".marker_arp_up";
        public static final String COL_MARKER_ARP_NORTH =  NAME + ".marker_arp_north";
        public static final String COL_MARKER_ARP_EAST =  NAME + ".marker_arp_east";
        public static final String COL_ALIGNMENT =  NAME + ".alignment";
        public static final String COL_NOTES =  NAME + ".notes";

        public static final String[] ARRAY = new String[] {
            COL_ID_MANUTENZIONE,COL_ID_SITO,COL_ID_ANTENNA,COL_DATE_INSTALLED,COL_DATE_REMOVED,COL_REFERENCE_POINT,COL_MARKER_ARP_UP,COL_MARKER_ARP_NORTH,COL_MARKER_ARP_EAST,COL_ALIGNMENT,COL_NOTES
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final MANUTENZIONE_ANTENNA table  = new  MANUTENZIONE_ANTENNA();
    }



    public static class MANUTENZIONE_RICEVITORE extends Tables {
        public static final String NAME = "manutenzione_ricevitore";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_ID_MANUTENZIONE =  NAME + ".id_manutenzione";
        public static final String COL_ID_SITO =  NAME + ".id_sito";
        public static final String COL_ID_RICEVITORE =  NAME + ".id_ricevitore";
        public static final String COL_DATE_INSTALLED =  NAME + ".date_installed";
        public static final String COL_DATE_REMOVED =  NAME + ".date_removed";
        public static final String COL_FIRMWARE_VERSION =  NAME + ".firmware_version";
        public static final String COL_ELEVATION_SETTINGS =  NAME + ".elevation_settings";
        public static final String COL_NOTES =  NAME + ".notes";

        public static final String[] ARRAY = new String[] {
            COL_ID_MANUTENZIONE,COL_ID_SITO,COL_ID_RICEVITORE,COL_DATE_INSTALLED,COL_DATE_REMOVED,COL_FIRMWARE_VERSION,COL_ELEVATION_SETTINGS,COL_NOTES
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final MANUTENZIONE_RICEVITORE table  = new  MANUTENZIONE_RICEVITORE();
    }



    public static class MONUMENTI_GPS extends Tables {
        public static final String NAME = "monumenti_gps";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_ID_MONUMENTO =  NAME + ".id_monumento";
        public static final String COL_DESCRIZIONE =  NAME + ".Descrizione";
        public static final String COL_TIPO =  NAME + ".Tipo";
        public static final String COL_NOTE =  NAME + ".Note";

        public static final String[] ARRAY = new String[] {
            COL_ID_MONUMENTO,COL_DESCRIZIONE,COL_TIPO,COL_NOTE
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final MONUMENTI_GPS table  = new  MONUMENTI_GPS();
    }



    public static class RETI extends Tables {
        public static final String NAME = "reti";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_ID_RETE =  NAME + ".id_rete";
        public static final String COL_SIGLA =  NAME + ".sigla";
        public static final String COL_DESCRIZIONE =  NAME + ".descrizione";
        public static final String COL_REFERENTE =  NAME + ".referente";
        public static final String COL_NOTE_ACQUISIZIONE =  NAME + ".note_acquisizione";

        public static final String[] ARRAY = new String[] {
            COL_ID_RETE,COL_SIGLA,COL_DESCRIZIONE,COL_REFERENTE,COL_NOTE_ACQUISIZIONE
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final RETI table  = new  RETI();
    }



    public static class SITI extends Tables {
        public static final String NAME = "siti";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_ID_SITO =  NAME + ".id_sito";
        public static final String COL_NOME_SITO =  NAME + ".nome_sito";
        public static final String COL_ID_RETE =  NAME + ".id_rete";
        public static final String COL_DATA_MATERIALIZZAZIONE =  NAME + ".data_materializzazione";
        public static final String COL_DATA_DISMISSIONE =  NAME + ".data_dismissione";
        public static final String COL_GEOLOGIA =  NAME + ".geologia";
        public static final String COL_LUOGO =  NAME + ".luogo";
        public static final String COL_LATITUDINE =  NAME + ".latitudine";
        public static final String COL_LONGITUDINE =  NAME + ".longitudine";
        public static final String COL_QUOTA =  NAME + ".quota";
        public static final String COL_X =  NAME + ".x";
        public static final String COL_Y =  NAME + ".y";
        public static final String COL_Z =  NAME + ".z";
        public static final String COL_X_UTMED50 =  NAME + ".x_utmed50";
        public static final String COL_Y_UTMED50 =  NAME + ".y_utmed50";
        public static final String COL_TIPO_MATERIALIZZAZIONE =  NAME + ".tipo_materializzazione";
        public static final String COL_HEIGHT_OF_MONUMENT =  NAME + ".height_of_monument";
        public static final String COL_MONUMENT_FOUNDATION =  NAME + ".monument_foundation";
        public static final String COL_FOUNDATION_DEPTH =  NAME + ".foundation_depth";
        public static final String COL_MONUMENT_INSCRIPTION =  NAME + ".monument_inscription";
        public static final String COL_IERS_DOMES_NUMBER =  NAME + ".iers_domes_number";
        public static final String COL_BEDROCK_TYPES =  NAME + ".bedrock_types";
        public static final String COL_ID_ON_SITE_AGENCY =  NAME + ".id_on_site_agency";
        public static final String COL_ID_RESPONSIBLE_AGENCY =  NAME + ".id_responsible_agency";
        public static final String COL_ID_MONUMENTO =  NAME + ".id_monumento";
        public static final String COL_NAZIONE =  NAME + ".nazione";
        public static final String COL_REGIONE =  NAME + ".regione";
        public static final String COL_ATTIVO =  NAME + ".attivo";
        public static final String COL_NOTE =  NAME + ".note";
        public static final String COL_ID_DATA_CENTER =  NAME + ".id_data_center";

        public static final String[] ARRAY = new String[] {
            COL_ID_SITO,COL_NOME_SITO,COL_ID_RETE,COL_DATA_MATERIALIZZAZIONE,COL_DATA_DISMISSIONE,COL_GEOLOGIA,COL_LUOGO,COL_LATITUDINE,COL_LONGITUDINE,COL_QUOTA,COL_X,COL_Y,COL_Z,COL_X_UTMED50,COL_Y_UTMED50,COL_TIPO_MATERIALIZZAZIONE,COL_HEIGHT_OF_MONUMENT,COL_MONUMENT_FOUNDATION,COL_FOUNDATION_DEPTH,COL_MONUMENT_INSCRIPTION,COL_IERS_DOMES_NUMBER,COL_BEDROCK_TYPES,COL_ID_ON_SITE_AGENCY,COL_ID_RESPONSIBLE_AGENCY,COL_ID_MONUMENTO,COL_NAZIONE,COL_REGIONE,COL_ATTIVO,COL_NOTE,COL_ID_DATA_CENTER
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final SITI table  = new  SITI();
    }



    public static class STRUMENTI_ANTENNA extends Tables {
        public static final String NAME = "strumenti_antenna";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_ID_ANTENNA =  NAME + ".id_antenna";
        public static final String COL_ANTENNA_TYPE =  NAME + ".antenna_type";
        public static final String COL_SERIAL_NUMBER =  NAME + ".serial_number";
        public static final String COL_RADOME_TYPE =  NAME + ".radome_type";
        public static final String COL_RADOME_SERIAL_NUMBER =  NAME + ".radome_serial_number";
        public static final String COL_CABLE_TYPE =  NAME + ".cable_type";
        public static final String COL_CABLE_LENGTH =  NAME + ".cable_length";

        public static final String[] ARRAY = new String[] {
            COL_ID_ANTENNA,COL_ANTENNA_TYPE,COL_SERIAL_NUMBER,COL_RADOME_TYPE,COL_RADOME_SERIAL_NUMBER,COL_CABLE_TYPE,COL_CABLE_LENGTH
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final STRUMENTI_ANTENNA table  = new  STRUMENTI_ANTENNA();
    }



    public static class STRUMENTI_RICEVITORE extends Tables {
        public static final String NAME = "strumenti_ricevitore";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_ID_RICEVITORE =  NAME + ".id_ricevitore";
        public static final String COL_RICEVITORE_TYPE =  NAME + ".ricevitore_type";
        public static final String COL_SISTEMA_SATELLITE =  NAME + ".sistema_satellite";
        public static final String COL_SERIAL_NUMBER =  NAME + ".serial_number";
        public static final String COL_TEMPERATURA_STABILIZ =  NAME + ".temperatura_stabiliz";

        public static final String[] ARRAY = new String[] {
            COL_ID_RICEVITORE,COL_RICEVITORE_TYPE,COL_SISTEMA_SATELLITE,COL_SERIAL_NUMBER,COL_TEMPERATURA_STABILIZ
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final STRUMENTI_RICEVITORE table  = new  STRUMENTI_RICEVITORE();
    }



    public static class STRUMENTI_SISTEMA extends Tables {
        public static final String NAME = "strumenti_sistema";

        public String getName() {return NAME;}
        public String getColumns() {return COLUMNS;}
        public static final String COL_ID_SISTEMA =  NAME + ".id_sistema";
        public static final String COL_ID_STRUMENTO =  NAME + ".id_strumento";

        public static final String[] ARRAY = new String[] {
            COL_ID_SISTEMA,COL_ID_STRUMENTO
        };
        public static final String COLUMNS = SqlUtil.comma(ARRAY);
        public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final STRUMENTI_SISTEMA table  = new  STRUMENTI_SISTEMA();
    }



}
